backend:
  name: github
  branch: dev
  repo: corallus/portfolio
  base_url: 'https://infaxka6yj.execute-api.eu-central-1.amazonaws.com'
  auth_endpoint: '/prod/auth'

media_folder: static/media
public_folder: /media

development_overrides:
  backend:
    name: file-system
    api_root: 'http://localhost:8000/api'

collections:
  - name: "education"
    label: "Education"
    folder: "src/content/education"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "study"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: image, required: false}
      - {label: "Degree", name: "degree", widget: "string"}
      - {label: "School", name: "school", widget: "string"}
      - {label: "Started", name: "started", widget: "date"}
      - {label: "Ended", name: "ended", widget: "date", required: false}
      - {label: "Description", name: "body", widget: "markdown", required: false}
  - name: "portfolio"
    label: "Portfolio"
    folder: "src/content/portfolio"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "project"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Website(s)", name: "websites", widget: "list", fields: [
        {label: "Name", name: "name", widget: "string"},
        {label: "Link", name: "link", widget: "string", required: false},
        {label: "Image", name: "image", widget: image, required: false}
      ]}
      - {label: "Link", name: "link", widget: "string", required: false}
      - {label: "Image", name: "image", widget: image, required: false}
      - {label: "Archive", name: "archive", widget: "boolean", required: false}
      - {label: "Toolset", name: "toolset", widget: "object", fields: [
        {label: "Django", name: "django", widget: "boolean", required: false},
        {label: "Wordpress", name: "wordpress", widget: "boolean", required: false},
        {label: "React", name: "react", widget: "boolean", required: false},
        {label: "Angular", name: "angular", widget: "boolean", required: false},
        {label: "Gatsby", name: "gatsby", widget: "boolean", required: false},
        {label: "Bootstrap", name: "bootstrap", widget: "boolean", required: false},
        {label: "Webpack", name: "webpack", widget: "boolean", required: false},
        {label: "Gulp", name: "gulp", widget: "boolean", required: false},
        {label: "jQuery", name: "jquery", widget: "boolean", required: false},
        {label: "Sass", name: "sass", widget: "boolean", required: false},
        {label: "AWS", name: "aws", widget: "boolean", required: false},
        {label: "Firebase", name: "firebase", widget: "boolean", required: false}
      ]}
      - {label: "Started", name: "started", widget: "date"}
      - {label: "Ended", name: "ended", widget: "date", required: false}
      - {label: "Description", name: "body", widget: "markdown", required: false}
  - name: "interests"
    label: "Interests"
    folder: "src/content/interests"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "interest"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: image, required: false}
      - {label: "Description", name: "body", widget: "markdown", required: false}
  - label: "Pages"
    name: "pages"
    files:
      - label: "About"
        name: "about"
        file: "src/content/about.md"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about"}
          - {label: Title, name: title, widget: string}
          - {label: Surname, name: surname, widget: string}
          - {label: Name, name: name, widget: string}
          - {label: Github, name: github, widget: string}
          - {label: LinkedIn, name: linkedin, widget: string}
          - {label: Description, name: body, widget: markdown}
          - {label: Skills, name: skills, widget: list, fields: [
              {label: Name, name: name, widget: string},
              {label: Skills, name: skills, widget: list, fields: [
                {label: Name, name: name, widget: string},
                {label: Skills, name: skills, widget: list, required: false}
              ]}
          ]}